# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentobject',
            name='result',
            field=models.NullBooleanField(),
        ),
    ]
