# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('identity', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_id', models.CharField(max_length=16)),
                ('e_mail', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(blank=True, max_length=64)),
                ('college', models.CharField(max_length=64)),
                ('grade', models.IntegerField()),
                ('description', models.TextField()),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.MyUser')),
            ],
        ),
    ]
