# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=16)),
                ('e_mail', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(blank=True, max_length=64)),
                ('cell_private', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.MyUser')),
            ],
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='identity_id',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='cell_private',
            field=models.BooleanField(default=False),
        ),
    ]
