# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20161116_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='college',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student_id',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
