# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20161116_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
