# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
